apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
    choerodon.io/infra: skywalking-ui
    choerodon.io/logs-parser: docker
    choerodon.io/release: skywalking-ui
  name: skywalking-ui
  namespace: skywalking-min
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
        choerodon.io/infra: skywalking-ui
        choerodon.io/release: skywalking-ui
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms1024M -Xmx1024M
        - name: collector.ribbon.ReadTimeout
          value: "100000"
        - name: collector.ribbon.listOfServers
          value: oap:12800
        image: registry.cn-shanghai.aliyuncs.com/vinkdong/skywalking-ui:v6.0.0-beta
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 8080
          name: page
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
