apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    release: es-min-kibana
  name: es-min-kibana-kibana
  namespace: es-min-kibana
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: es-min-kibana
  sessionAffinity: None
  type: ClusterIP
