apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    component: controller
    release: nginx-ingress-min
  name: nginx-ingress-min-controller
  namespace: nginx-ingress-min
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31873
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30235
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
    component: controller
    release: nginx-ingress-min
  sessionAffinity: None
  type: LoadBalancer
