apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ingress-controller-leader-nginx
    namespace: nginx-ingress-min
- apiVersion: v1
  data:
    enable-vts-status: "false"
  kind: ConfigMap
  metadata:
    labels:
      app: nginx-ingress
      component: controller
      release: nginx-ingress-min
    name: nginx-ingress-min-controller
    namespace: nginx-ingress-min
kind: List
