apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: nginx-ingress
      release: nginx-ingress-min
    name: nginx-ingress-min
    namespace: nginx-ingress-min
  secrets:
  - name: nginx-ingress-min-token
kind: List
