---
kind: Service
apiVersion: v1
metadata:
  namespace: rocketmq-min
  name: service-rocketmq-min-c0-namesrv-prod
  labels:
    app: service-rocketmq-min-c0-namesrv-prod
spec:
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 9876
  selector:
    app: pod-rocketmq-min-c0-namesrv-prod
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: rocketmq-min
  name: statefulset-rocketmq-min-c0-namesrv-prod
  labels:
    app: statefulset-rocketmq-min-c0-namesrv-prod
spec:
  replicas: 1
  serviceName: service-rocketmq-min-c0-namesrv-prod
  selector:
    matchLabels:
      app: pod-rocketmq-min-c0-namesrv-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-min-c0-namesrv-prod
    spec:
#      nodeSelector:
#        node-role.kubernetes.io/rocketmq: "true"
      #imagePullSecrets:
      #- name: hpy
      containers:
      - image: hpy253215039/rocketmq-namesrv:v4.3.2
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        name: container-rocketmq-min-c0-namesrv-prod
        ports:
        - protocol: TCP
          containerPort: 9876

        resources:
          requests:
            cpu: 0.1
            #memory: 1740Mi
            memory: 200Mi
          limits:
            cpu: 1
            #memory: 2048Mi
            memory: 200Mi
        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 120
          periodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-rocketmq-min-c0-namesrv-prod
              topologyKey: kubernetes.io/hostname

      dnsPolicy: ClusterFirst
      restartPolicy: Always
