apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-06-07T07:37:51Z"
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-8.10.0
    component: pushgateway
    heritage: Tiller
    release: dusty-kiwi
  name: dusty-kiwi-prometheus-pushgateway
  namespace: prometheus-min
  resourceVersion: "2001986"
  selfLink: /apis/apps/v1/namespaces/prometheus-min/deployments/dusty-kiwi-prometheus-pushgateway
  uid: 277dac8c-88f7-11e9-8122-00163e0266b8
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: prometheus
      component: pushgateway
      release: dusty-kiwi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        chart: prometheus-8.10.0
        component: pushgateway
        heritage: Tiller
        release: dusty-kiwi
    spec:
      containers:
      - image: prom/pushgateway:v0.6.0
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        ports:
        - containerPort: 9091
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /#/status
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dusty-kiwi-prometheus-pushgateway
      serviceAccountName: dusty-kiwi-prometheus-pushgateway
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-07T07:37:51Z"
    lastUpdateTime: "2019-06-07T07:37:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
