apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-min-alertmanager-pv-local
  namespace: prometheus-min
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "prometheus-min-alertmanager-storageclass-local"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/prometheus-min-alertmanager-pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-min-server-pv-local
  namespace: prometheus-min
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "prometheus-min-server-storageclass-local"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/prometheus-min-server-pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

