apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: prometheus
      component: alertmanager
      release: prometheus-min
    name: prometheus-min-alertmanager
    namespace: prometheus-min
  secrets:
  - name: prometheus-min-alertmanager-token
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: prometheus
      component: kube-state-metrics
      release: prometheus-min
    name: prometheus-min-kube-state-metrics
    namespace: prometheus-min
  secrets:
  - name: prometheus-min-kube-state-metrics-token
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: prometheus
      component: node-exporter
      release: prometheus-min
    name: prometheus-min-node-exporter
    namespace: prometheus-min
  secrets:
  - name: prometheus-min-node-exporter-token
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: prometheus
      component: pushgateway
      release: prometheus-min
    name: prometheus-min-pushgateway
    namespace: prometheus-min
  secrets:
  - name: prometheus-min-pushgateway-token
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: prometheus
      component: server
      release: prometheus-min
    name: prometheus-min-server
    namespace: prometheus-min
  secrets:
  - name: prometheus-min-server-token
kind: List
