apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-nginx
    component: default-backend
    release: ingress-nginx
  name: ingress-nginx-default-backend
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: ingress-nginx
    component: default-backend
    release: ingress-nginx
  sessionAffinity: None
  type: ClusterIP
