apiVersion: v1
kind: Service
metadata:
  name: es-min-c0-ingest
  namespace: elasticsearch
  labels:
    app: es-min-c0-ingest-service
  annotations:
      service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
      service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: es-min-c0-ingest
    chart: elasticsearch-6.4.3
    heritage: Tiller
    release: es-min-c0-ingest
  type: ClusterIP
