apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-min-data0-pv-local
  namespace: elasticsearch
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "es-min-data-pv-local"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/es-min-data0-pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future
